# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.daemon=true
android.useAndroidX=true

# 版本号在 CI 与本地构建共用
appVersionName=1.1.0
appVersionCode=3

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
